"""Filesystem locations for the project.

`data/` is gitignored with one deliberate exception: `data/events/`, which
holds the hand-curated event dictionary. That file is *source*, not data --
it cannot be regenerated by a loader, so it is version controlled. See the
note at the top of `.gitignore`.

Nothing in this module creates anything outside the project tree.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT: Path = Path(__file__).resolve().parents[2]

CONFIG_DIR: Path = PROJECT_ROOT / "config"
UNIVERSE_CONFIG: Path = CONFIG_DIR / "universe.yaml"

DATA_DIR: Path = PROJECT_ROOT / "data"
RAW_DIR: Path = DATA_DIR / "raw"
INTERIM_DIR: Path = DATA_DIR / "interim"
PROCESSED_DIR: Path = DATA_DIR / "processed"

#: Hand-curated event dictionary. Version controlled, unlike everything else
#: under `data/`.
EVENTS_DIR: Path = DATA_DIR / "events"
EVENTS_CSV: Path = EVENTS_DIR / "uk_energy_policy_events.csv"

DOCS_DIR: Path = PROJECT_ROOT / "docs"
REPORTS_DIR: Path = PROJECT_ROOT / "reports"
FIGURES_DIR: Path = REPORTS_DIR / "figures"
TABLES_DIR: Path = REPORTS_DIR / "tables"


def ensure_dirs() -> None:
    """Create the data and report output directories if they are absent."""
    for directory in (
        RAW_DIR,
        INTERIM_DIR,
        PROCESSED_DIR,
        EVENTS_DIR,
        FIGURES_DIR,
        TABLES_DIR,
    ):
        directory.mkdir(parents=True, exist_ok=True)
