"""Render the sweep into `data/events/candidates.md`. Protocol Steps 1-3.

Fills in only what a primary source can answer:

* the announcement's first publication, from the gov.uk content API's change
  history -- never from the search API's `public_timestamp`, which is the
  last-updated stamp;
* whether a time of day was recorded at all;
* how that timestamp resolves against LSE trading hours, and therefore which
  trading day `t0` would fall on.

It fills in **nothing** that requires judgement. `anticipation_risk`,
`surprise_note`, `direction` and the Step 2 leak check are left explicitly
blank and marked, because guessing them is the failure the protocol's Rule 0
exists to prevent.
"""

from __future__ import annotations

import sys

import pandas as pd

from policy_event_study.events.schema import resolve_event_timing
from policy_event_study.paths import EVENTS_DIR

#: Document types that can carry a datable policy decision. Guidance pages are
#: living documents -- updated far more often than announced -- so their change
#: history dates page creation rather than a decision.
ANNOUNCEMENT_TYPES = {
    "press_release",
    "news_story",
    "speech",
    "written_statement",
    "oral_statement",
    "consultation_outcome",
    "policy_paper",
}

#: Titles matching these are promotional or statistical rather than decisions:
#: uptake figures, explainers, case studies. Excluded by rule and the rule is
#: printed, so the exclusion is auditable rather than a silent judgement call.
NOT_A_DECISION = (
    "applications surge",
    "applications up",
    "grant applications",
    "in demand",
    "demand for heat pumps",
    "reasons to get",
    "explained",
    "what you need to know",
    "case study",
    "statistics show",
    "research reveals",
    "satisfaction among",
)


def main() -> int:
    """Build the candidate table from the newest sweep."""
    sweeps = sorted(EVENTS_DIR.glob("govuk_sweep_*.csv"))
    if not sweeps:
        print("no sweep found; run `make sweep` first")
        return 1
    source = sweeps[-1]
    vintage = source.stem.replace("govuk_sweep_", "")

    frame = pd.read_csv(source)
    frame["first_published_at"] = pd.to_datetime(
        frame["first_published_at"], utc=True, format="mixed"
    )
    total = len(frame)

    frame = frame[frame["document_type"].isin(ANNOUNCEMENT_TYPES)]
    frame = frame[frame["first_published_at"] >= "2013-01-01"]
    lowered = frame["title"].str.lower()
    frame = frame[~lowered.str.contains("|".join(NOT_A_DECISION), regex=True, na=False)]
    frame = frame.sort_values("first_published_at").reset_index(drop=True)

    calendar = pd.DatetimeIndex(
        pd.bdate_range(
            frame["first_published_at"].min() - pd.Timedelta(days=10),
            frame["first_published_at"].max() + pd.Timedelta(days=10),
            tz="UTC",
        )
    )

    rows: list[dict[str, object]] = []
    for _, record in frame.iterrows():
        stamp = record["first_published_at"]
        london = stamp.tz_convert("Europe/London")
        time_known = not (london.hour == 0 and london.minute == 0)
        try:
            timing = resolve_event_timing(stamp, calendar, time_known=bool(time_known))
            t0 = str(timing.t0.date())
            straddles = (
                str(timing.straddling_day.date())
                if timing.straddling_day is not None
                else "-"
            )
        except ValueError:
            t0, straddles = "-", "-"
        rows.append(
            {
                "first_published_utc": str(stamp)[:16],
                "london": str(london)[:16],
                "time_known": time_known,
                "t0": t0,
                "straddles": straddles,
                "type": record["document_type"],
                "title": str(record["title"]),
                "url": str(record["url"]),
            }
        )

    lines = [
        "# Event candidates — working list",
        "",
        f"Generated by `scripts/build_candidates.py` from `{source.name}` "
        f"(sweep vintage {vintage}).",
        "**Regenerate rather than edit.** Promote rows into "
        "`uk_energy_policy_events.csv` once Steps 2, 4 and 5 are done.",
        "",
        "## What is filled in, and what is not",
        "",
        "| Filled by rule | Left blank — needs judgement |",
        "|---|---|",
        "| First publication, from the content API's change history | Step 2 leak check |",
        "| Whether a time of day was recorded | `anticipation_risk` |",
        "| LSE resolution: `t0` and any straddling day | `surprise_note` |",
        "| Document type and primary-source URL | `direction`, `channel_targets` |",
        "",
        "**No row below has had its Step 2 leak check.** The dates are formal "
        "publication, not first public disclosure. For any announcement that was "
        "briefed to journalists the evening before, the true event date is "
        "earlier and `t0` shifts with it — see the standing note under the table.",
        "",
        "## Sourcing rule",
        "",
        "**Primary sources only.** The gov.uk **content** API is authoritative "
        "for first publication; the **search** API's `public_timestamp` is the "
        "last-updated stamp and must never be used as an announcement date. "
        "Across this sweep the two differ by a median of 56 days and a maximum "
        "of 6,308 days.",
        "",
        "News coverage is admissible for exactly one purpose: establishing that "
        "an announcement was trailed beforehand, which sets `leak_note` and "
        "feeds `anticipation_risk`. It is never the source for "
        "`announcement_timestamp_utc`.",
        "",
        "## Filtering applied",
        "",
        f"- Swept: {total} gov.uk items across "
        "12 technical and 4 cross-cutting queries",
        f"- Kept document types: {', '.join(sorted(ANNOUNCEMENT_TYPES))}",
        "- Kept first publication from 2013 onward",
        "- Dropped uptake statistics, explainers and case studies by title rule "
        f"({len(NOT_A_DECISION)} patterns, listed in the script)",
        f"- **{len(rows)} candidates remain**",
        "",
        "> **Recall warning — read before trusting this list.** The first sweep "
        "> used technical vocabulary only and did not surface the September 2023 "
        "> net-zero rollback, the event `docs/data_inventory.md` §8 calls the "
        "> highest-value single event in the study. Cross-cutting queries were "
        "> added and the rollback now appears as its **press release** "
        "> (2023-09-20 16:13 UTC). The **speech** of the same announcement "
        "> (`/government/speeches/pm-speech-on-net-zero-20-september-2023`, "
        "> first published 16:24 UTC) is indexed by gov.uk but is not returned "
        "> by any of the 16 sweep queries.",
        ">",
        "> The general lesson is structural, not a bug to be fixed: large "
        "> directional announcements are written in general language, scheme "
        "> adjustments in technical language, and a category sweep ranks the "
        "> latter. **Recall is a property of the query list and cannot be "
        "> assumed complete.** Known events should be added by hand and dated "
        "> through `events.govuk.first_publication`, which reads the content "
        "> API directly and applies the same timestamp discipline.",
        "",
        "## Candidates",
        "",
        "`t0` is the trading day the event window would open on, under the "
        "LSE open/close convention. A `straddles` entry means that day's "
        "close-to-close return spans the announcement and is excluded from day 0.",
        "",
        "| # | First published (UTC) | London | Time? | t0 | Straddles | Type | Title |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for index, row in enumerate(rows, start=1):
        title = f"[{row['title']}]({row['url']})"
        lines.append(
            f"| {index} | {row['first_published_utc']} | {row['london']} | "
            f"{'yes' if row['time_known'] else '**no**'} | {row['t0']} | "
            f"{row['straddles']} | {row['type']} | {title} |"
        )

    known = sum(1 for row in rows if row["time_known"])
    lines += [
        "",
        f"**Time of day recoverable for {known} of {len(rows)}.** The rest carry "
        "a midnight stamp, meaning gov.uk never recorded a time. Those rows take "
        "`time_known=false` and the conservative event-day convention, which "
        "treats the whole announcement day as straddling. Do not guess a time.",
        "",
        "## Before promoting any row",
        "",
        "1. **Step 2 leak check** — search the preceding 10 calendar days for "
        "reporting of the *substance*. If it appeared earlier, the event date is "
        "the earlier one and both timestamps are recorded. If disclosure was "
        "gradual, drop the event and say why.",
        "2. **Step 4 surprise** — `surprise_note` names the specific "
        "unanticipated parameter, not a summary. `anticipation_risk` by the "
        "rule in the protocol, not by feeling. Keep the `high` ones: they are "
        "the natural placebo group.",
        "3. **Step 5 fields** — `direction` needs a real mix of `tighten` and "
        "`loosen`, and each side needs enough events to reach significance "
        "alone. Three tightenings and one loosening yields `UNDERPOWERED` and "
        "tells you nothing.",
        "4. **Step 6 grouping** — run `make event-report`; events within 14 days "
        "collapse into one cluster by transitive closure, and the bootstrap "
        "p-value floor is computed from the group count.",
        "",
        "## Promoted",
        "",
        "_None yet._",
        "",
    ]

    target = EVENTS_DIR / "candidates.md"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(rows)} candidates -> {target}")
    print(f"  time of day recoverable: {known}")
    print(
        f"  span: {rows[0]['first_published_utc']} .. {rows[-1]['first_published_utc']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
